# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'runge_kutt.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_runge_kutt_window(object):
    def setupUi(self, runge_kutt_window):
        runge_kutt_window.setObjectName("runge_kutt_window")
        runge_kutt_window.resize(658, 335)
        runge_kutt_window.setMinimumSize(QtCore.QSize(658, 335))
        runge_kutt_window.setMaximumSize(QtCore.QSize(658, 335))
        font = QtGui.QFont()
        font.setPointSize(16)
        runge_kutt_window.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(runge_kutt_window)
        self.buttonBox.setGeometry(QtCore.QRect(480, 300, 171, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.func_label = QtWidgets.QLabel(runge_kutt_window)
        self.func_label.setGeometry(QtCore.QRect(10, 30, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.func_label.setFont(font)
        self.func_label.setObjectName("func_label")
        self.x0_label = QtWidgets.QLabel(runge_kutt_window)
        self.x0_label.setGeometry(QtCore.QRect(40, 90, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.x0_label.setFont(font)
        self.x0_label.setObjectName("x0_label")
        self.y0_label = QtWidgets.QLabel(runge_kutt_window)
        self.y0_label.setGeometry(QtCore.QRect(40, 160, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.y0_label.setFont(font)
        self.y0_label.setObjectName("y0_label")
        self.a_label = QtWidgets.QLabel(runge_kutt_window)
        self.a_label.setGeometry(QtCore.QRect(240, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.a_label.setFont(font)
        self.a_label.setObjectName("a_label")
        self.b_label = QtWidgets.QLabel(runge_kutt_window)
        self.b_label.setGeometry(QtCore.QRect(240, 160, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.b_label.setFont(font)
        self.b_label.setObjectName("b_label")
        self.func_line_edit = QtWidgets.QLineEdit(runge_kutt_window)
        self.func_line_edit.setGeometry(QtCore.QRect(90, 30, 220, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.func_line_edit.setFont(font)
        self.func_line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.func_line_edit.setObjectName("func_line_edit")
        self.x0_line_edit = QtWidgets.QLineEdit(runge_kutt_window)
        self.x0_line_edit.setGeometry(QtCore.QRect(90, 90, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.x0_line_edit.setFont(font)
        self.x0_line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.x0_line_edit.setObjectName("x0_line_edit")
        self.a_line_edit = QtWidgets.QLineEdit(runge_kutt_window)
        self.a_line_edit.setGeometry(QtCore.QRect(280, 90, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.a_line_edit.setFont(font)
        self.a_line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.a_line_edit.setObjectName("a_line_edit")
        self.y0_line_edit = QtWidgets.QLineEdit(runge_kutt_window)
        self.y0_line_edit.setGeometry(QtCore.QRect(90, 160, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.y0_line_edit.setFont(font)
        self.y0_line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.y0_line_edit.setObjectName("y0_line_edit")
        self.b_line_edit = QtWidgets.QLineEdit(runge_kutt_window)
        self.b_line_edit.setGeometry(QtCore.QRect(280, 160, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.b_line_edit.setFont(font)
        self.b_line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.b_line_edit.setObjectName("b_line_edit")
        self.x_y_table = QtWidgets.QTableWidget(runge_kutt_window)
        self.x_y_table.setEnabled(True)
        self.x_y_table.setGeometry(QtCore.QRect(340, 30, 311, 191))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.x_y_table.setFont(font)
        self.x_y_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.x_y_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.x_y_table.setRowCount(5)
        self.x_y_table.setColumnCount(3)
        self.x_y_table.setObjectName("x_y_table")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.x_y_table.setItem(0, 0, item)
        self.x_y_table.horizontalHeader().setVisible(True)
        self.x_y_table.horizontalHeader().setCascadingSectionResizes(False)
        self.x_y_table.verticalHeader().setVisible(False)

        self.retranslateUi(runge_kutt_window)
        # self.buttonBox.accepted.connect(runge_kutt_window.accept)
        # self.buttonBox.rejected.connect(runge_kutt_window.reject)
        QtCore.QMetaObject.connectSlotsByName(runge_kutt_window)

    def retranslateUi(self, runge_kutt_window):
        _translate = QtCore.QCoreApplication.translate
        runge_kutt_window.setWindowTitle(_translate("runge_kutt_window", "Метод Рунге-Кутта"))
        self.func_label.setText(_translate("runge_kutt_window", "f(x, y)"))
        self.x0_label.setText(_translate("runge_kutt_window", "x0"))
        self.y0_label.setText(_translate("runge_kutt_window", "y0"))
        self.a_label.setText(_translate("runge_kutt_window", "a"))
        self.b_label.setText(_translate("runge_kutt_window", "b"))
        self.func_line_edit.setText(_translate("runge_kutt_window", "x + y"))
        self.x0_line_edit.setText(_translate("runge_kutt_window", "0"))
        self.a_line_edit.setText(_translate("runge_kutt_window", "0"))
        self.y0_line_edit.setText(_translate("runge_kutt_window", "0"))
        self.b_line_edit.setText(_translate("runge_kutt_window", "0"))
        __sortingEnabled = self.x_y_table.isSortingEnabled()
        self.x_y_table.setSortingEnabled(False)
        self.x_y_table.setSortingEnabled(__sortingEnabled)
